name: "Python Setup"
description: "Python Setup, install dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: pip

    - run: pip install -r requirements.txt
      shell: bash
