name: 'USD/JPY Pipeline'

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-setup
      - name: Buid Code
        run: echo "Nothing to build for this Python project."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-setup
      - name: Execute Unit Test
        run:  echo "Place code to run tests here"

  run:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-setup
      - name: 'Fetch USD/JPY'
        run: python fetch.py
        env:
          EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}

      - name: Process data
        run: python process.py

      - name: Analyze data
        run: python analyze.py

      - name: Commit updated dataset
        run: ./scripts/commit_data.sh

  kagggle:
    runs-on: ubuntu-latest
    needs: run
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-setup
      - name: Install Kaggle API
        run: pip install kaggle
        
      - name: Push dataset to Kaggle
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
          KAGGLE_DIR: $HOME/kaggle
        run: |
          mkdir -p ${{ env.KAGGLE_DIR }}
          kaggle datasets version -p ${{ env.KAGGLE_DIR }}/data -m "Update dataset"
